# Generated by Django 5.0.2 on 2024-03-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_type_customuser_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subject',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
