# Generated by Django 5.0.2 on 2024-03-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='tutor',
        ),
        migrations.AddField(
            model_name='reservation',
            name='student_username',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tutor_username',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
